version: '2'
services:
  node:
    image: node:19-alpine
    volumes:
      - ./app:/app
    working_dir: /app
    command: 
      - /bin/sh
      - -c
      - |
        npm i react-admin ra-data-json-server
        yarn create vite test-admin --template react-ts
        cd test-admin
        yarn
        cp ../src/index.html .
        cp ../src/src/* src/
        yarn dev --host
    ports:
      - '7777:5173'

